steps:
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", 'app.yaml', '--version=cd', '--promote']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", 'app-frontend.yaml', '--version=cd', '--promote']
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy", 'app-cron.yaml', '--version=cd', '--promote']
timeout: "4800s"
